version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "@docker123"
    ports:
      - "1433:1433"
    restart: always
